[package]
name = "mixie"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.1"
cpal = "0.13.5"
crossbeam = "0.8.1"
parking_lot = "0.12.0"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "fmt"] }
